import {
  best_product_1,
  best_product_2,
  best_product_3,
  best_product_4,
  flash_1,
  flash_2,
  flash_3,
  flash_4,
  image_57,
  image_58,
  image_59,
  image_60,
  image_61,
  ourproduct_1,
  ourproduct_2,
  ourproduct_3,
  ourproduct_4,
  ourproduct_5,
  ourproduct_6,
  ourproduct_7,
  ourproduct_8,
} from "../assets";
export const data = [
  {
    id: "1",
    name: "HAVIT HV-G92 Gamepad",
    title: "HAVIT HV-G92 Gamepad",
    price: "$160",
    img: flash_1,
    desc: "$120",
    rating: 4,
    discount_rate: "-40%",
    quantity: 1,
  },
  {
    id: "2",
    name: "AK-900 Wired Keyboard",
    title: "AK-900 Wired Keyboard",
    price: "$160",
    img: flash_2,
    desc: "$960",
    rating: 3,
    discount_rate: "-35%",
    quantity: 1,
  },
  {
    id: "3",
    name: "IPS LCD Gaming Monitor",
    title: "IPS LCD Gaming Monitor",
    price: "$160",
    img: flash_3,
    desc: "$370",
    rate: 2,
    discount_rate: "-30%",
    quantity: 1,
  },
  {
    id: "4",
    name: "S-Series Comfort Chair",
    title: "S-Series Comfort Chair ",
    price: "$160",
    img: flash_4,
    desc: "$375",
    rating: 4,
    discount_rate: "-25%",
    quantity: 1,
  },
];

export const products = [
  {
    id: "5",
    name: "The north coat",
    title: "The north coat",
    price: "$360",
    img: best_product_1,
    desc: "$260",
    rating: 0,
    discount_rate: "-40%",
    quantity: 1,
  },
  {
    id: "6",
    name: "Gucci duffle bag",
    title: "Gucci duffle bag",
    price: "$1160",
    img: best_product_2,
    desc: "$960",
    rating: 0,
    discount_rate: "-35%",
    quantity: 1,
  },
  {
    id: "7",
    name: "RGB liquid CPU Cooler",
    title: "RGB liquid CPU Cooler",
    price: "$170",
    img: best_product_3,
    desc: "$160",
    rate: 0,
    discount_rate: "-30%",
    quantity: 1,
  },
  {
    id: "8",
    name: "Small BookSelf",
    title: "Small BookSelf",
    price: "$360",
    img: best_product_4,
    // desc: "$375",
    rating: 0,
    discount_rate: "-25%",
    quantity: 1,
  },
];

export const ourProducts = [
  {
    id: "9",
    name: "The north coat",
    title: "The north coat",
    price: "$100",
    img: ourproduct_1,
    rating: 3,
    quantity: 1,
  },
  {
    id: "10",
    name: "Gucci duffle bag",
    title: "Gucci duffle bag",
    price: "$360",
    img: ourproduct_2,
    rating: 4,
    quantity: 1,
  },
  {
    id: "11",
    name: "RGB liquid CPU Cooler",
    title: "RGB liquid CPU Cooler",
    price: "$700",
    img: ourproduct_3,
    rating: 2,
    quantity: 1,
  },
  {
    id: "12",
    name: "Small BookSelf",
    title: "Small BookSelf",
    price: "$500",
    img: ourproduct_4,
    rating: 3,
    quantity: 1,
  },
  {
    id: "13",
    name: "The north coat",
    title: "The north coat",
    price: "$960",
    img: ourproduct_5,
    rating: 4,
    quantity: 1,
  },
  {
    id: "14",
    name: "Gucci duffle bag",
    title: "Gucci duffle bag",
    price: "$1160",
    img: ourproduct_6,
    rating: 2,
    quantity: 1,
  },
  {
    id: "15",
    name: "RGB liquid CPU Cooler",
    title: "RGB liquid CPU Cooler",
    price: "$660",
    img: ourproduct_7,
    rating: 1,
    quantity: 1,
  },
  {
    id: "16",
    name: "Small BookSelf",
    title: "Small BookSelf",
    price: "$660",
    img: ourproduct_8,
    rating: 5,
    quantity: 1,
  },
  {
    id: "17",
    name: "Havic HV G-92 Gamepad",
    title: "Havic HV G-92 Gamepad",
    price: "$192.00",
    img: image_61,
    rating: 5,
    quantity: 1,
    images: [
      image_61,
      image_57,
      image_58,
      image_59,
      image_60,
      
    ],
    description: [
      "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive."
    ],
    colors: [
      "Red",
      "Blue",
      "Black",
    ],
    sizes: [
      "xs",
      "s",
      "m",
      "l",
      "xl",
    ],
  },
];
